* `generator.throw(exec_type[, exec_value[, traceback]])`:致使生成器在暂停的yield表达式处抛出指定的异常。如果生成器
处理了抛出的异常，代码会向前执行到下一个yield表达式，而产生的值会成为调用generator.throw方法得到的返回值。如果生成器
没有处理抛出的异常，异常会向上冒泡，传到调用方的上下文中。
* `generator.close()`： 致使生成器在暂停的yield表达式处抛出GeneratorExit异常。如果生成器没有处理这个异常，或者抛出了
StopIteration异常，调用方不会报错。如果收到GeneratorExit异常，生成器一定不能产出值，否则解释器会抛出RuntimeError异常。
生成器抛出的其它异常会向上冒泡，传递给调用方。

